-- Unique migration version; this SQL was originally applied manually on 2026-07-22.
-- Public creator profiles, case-insensitive username uniqueness, and a
-- database-enforced rolling limit of three username changes per year.

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  avatar_url text,
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_username_format check (
    username = btrim(username)
    and char_length(username) between 3 and 30
    and username ~ '^[A-Za-z0-9_][A-Za-z0-9 _.-]{2,29}$'
  )
);

create unique index if not exists user_profiles_username_lower_uidx
  on public.user_profiles (lower(username));

create table if not exists public.user_username_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  old_username text not null,
  new_username text not null,
  changed_at timestamptz not null default now()
);

create index if not exists user_username_changes_user_time_idx
  on public.user_username_changes (user_id, changed_at desc);

alter table public.user_profiles enable row level security;
alter table public.user_username_changes enable row level security;

drop policy if exists "Public profiles are readable" on public.user_profiles;
create policy "Public profiles are readable"
  on public.user_profiles for select
  using (true);

drop policy if exists "Users can read their username history" on public.user_username_changes;
create policy "Users can read their username history"
  on public.user_username_changes for select
  using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-avatars',
  'profile-avatars',
  true,
  1048576,
  array['image/webp', 'image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Avatar images are publicly readable" on storage.objects;
create policy "Avatar images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'profile-avatars');

drop policy if exists "Users can upload their own avatar" on storage.objects;
create policy "Users can upload their own avatar"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can update their own avatar" on storage.objects;
create policy "Users can update their own avatar"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can delete their own avatar" on storage.objects;
create policy "Users can delete their own avatar"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'profile-avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create or replace function public.profile_username_base(p_value text)
returns text
language sql
immutable
as $$
  select case
    when char_length(v) >= 3 and v ~ '^[A-Za-z0-9_]' then left(v, 23)
    when char_length(v) >= 2 then left('u_' || v, 23)
    else 'creator'
  end
  from (
    select btrim(
      regexp_replace(
        regexp_replace(coalesce(p_value, ''), '[^A-Za-z0-9 _.-]+', '', 'g'),
        '\s+', ' ', 'g'
      )
    ) as v
  ) cleaned;
$$;

create or replace function public.ensure_my_user_profile()
returns public.user_profiles
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user auth.users%rowtype;
  v_profile public.user_profiles%rowtype;
  v_base text;
  v_candidate text;
  v_attempt integer := 0;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select * into v_profile from public.user_profiles where user_id = auth.uid();
  if found then return v_profile; end if;

  select * into v_user from auth.users where id = auth.uid();
  v_base := public.profile_username_base(
    coalesce(v_user.raw_user_meta_data ->> 'name', split_part(v_user.email, '@', 1))
  );

  loop
    v_candidate := case
      when v_attempt = 0 then v_base
      else left(v_base, 21) || '_' || substr(md5(auth.uid()::text || v_attempt::text), 1, 6)
    end;
    begin
      insert into public.user_profiles (user_id, username, avatar_url)
      values (auth.uid(), v_candidate, v_user.raw_user_meta_data ->> 'avatar_url')
      returning * into v_profile;
      return v_profile;
    exception when unique_violation then
      v_attempt := v_attempt + 1;
      if v_attempt > 20 then
        raise exception 'USERNAME_PROVISIONING_FAILED';
      end if;
    end;
  end loop;
end;
$$;

create or replace function public.get_my_profile()
returns table (
  user_id uuid,
  username text,
  avatar_url text,
  avatar_path text,
  username_changes_used integer,
  username_changes_remaining integer,
  next_username_change_reset_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_profile public.user_profiles%rowtype;
begin
  v_profile := public.ensure_my_user_profile();
  return query
  select
    v_profile.user_id,
    v_profile.username,
    v_profile.avatar_url,
    v_profile.avatar_path,
    count(c.id)::integer,
    greatest(0, 3 - count(c.id)::integer),
    min(c.changed_at) + interval '1 year'
  from public.user_username_changes c
  where c.user_id = v_profile.user_id
    and c.changed_at > now() - interval '1 year';
end;
$$;

create or replace function public.check_username_availability(p_username text)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_username text := btrim(coalesce(p_username, ''));
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if char_length(v_username) not between 3 and 30
    or v_username !~ '^[A-Za-z0-9_][A-Za-z0-9 _.-]{2,29}$' then
    return false;
  end if;
  return not exists (
    select 1 from public.user_profiles p
    where lower(p.username) = lower(v_username)
      and p.user_id <> auth.uid()
  );
end;
$$;

create or replace function public.update_my_profile(
  p_username text,
  p_avatar_url text default null,
  p_avatar_path text default null
)
returns table (
  user_id uuid,
  username text,
  avatar_url text,
  avatar_path text,
  username_changes_used integer,
  username_changes_remaining integer,
  next_username_change_reset_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_profile public.user_profiles%rowtype;
  v_username text := btrim(coalesce(p_username, ''));
  v_changes integer;
begin
  v_profile := public.ensure_my_user_profile();

  if char_length(v_username) not between 3 and 30
    or v_username !~ '^[A-Za-z0-9_][A-Za-z0-9 _.-]{2,29}$' then
    raise exception 'USERNAME_INVALID' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext(lower(v_username)));
  if exists (
    select 1 from public.user_profiles p
    where lower(p.username) = lower(v_username)
      and p.user_id <> auth.uid()
  ) then
    raise exception 'USERNAME_TAKEN' using errcode = '23505';
  end if;

  if v_profile.username <> v_username then
    select count(*)::integer into v_changes
    from public.user_username_changes c
    where c.user_id = auth.uid()
      and c.changed_at > now() - interval '1 year';
    if v_changes >= 3 then
      raise exception 'USERNAME_CHANGE_LIMIT_REACHED' using errcode = 'P0001';
    end if;
    insert into public.user_username_changes (user_id, old_username, new_username)
    values (auth.uid(), v_profile.username, v_username);
  end if;

  update public.user_profiles p set
    username = v_username,
    avatar_url = coalesce(p_avatar_url, p.avatar_url),
    avatar_path = coalesce(p_avatar_path, p.avatar_path),
    updated_at = now()
  where p.user_id = auth.uid();

  return query select * from public.get_my_profile();
end;
$$;

revoke all on function public.ensure_my_user_profile() from public;
revoke all on function public.get_my_profile() from public;
revoke all on function public.check_username_availability(text) from public;
revoke all on function public.update_my_profile(text, text, text) from public;
grant execute on function public.ensure_my_user_profile() to authenticated;
grant execute on function public.get_my_profile() to authenticated;
grant execute on function public.check_username_availability(text) to authenticated;
grant execute on function public.update_my_profile(text, text, text) to authenticated;

-- Backfill existing accounts. A short hash is only appended when two users
-- would otherwise receive the same case-insensitive default username.
do $$
declare
  v_user auth.users%rowtype;
  v_base text;
  v_candidate text;
  v_attempt integer;
begin
  for v_user in select * from auth.users order by created_at, id loop
    if exists (select 1 from public.user_profiles where user_id = v_user.id) then
      continue;
    end if;
    v_base := public.profile_username_base(
      coalesce(v_user.raw_user_meta_data ->> 'name', split_part(v_user.email, '@', 1))
    );
    v_attempt := 0;
    loop
      v_candidate := case
        when v_attempt = 0 then v_base
        else left(v_base, 21) || '_' || substr(md5(v_user.id::text || v_attempt::text), 1, 6)
      end;
      begin
        insert into public.user_profiles (user_id, username, avatar_url)
        values (v_user.id, v_candidate, v_user.raw_user_meta_data ->> 'avatar_url');
        exit;
      exception when unique_violation then
        v_attempt := v_attempt + 1;
      end;
    end loop;
  end loop;
end;
$$;
